export const SHOW_HIDE_CART = "SHOW_HIDE_CART";
export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_ITEM = "REMOVE_ITEM";
export const CHANGE_CART_QTY = "CHANGE_CART_QTY";
export const CHANGE_CART_SIZE = "CHANGE_CART_SIZE";
export const LOAD_CART_FROM_STORAGE = "LOAD_CART_FROM_STORAGE";
